### ISSUE TITLE
How about products in Commerce?

### ISSUE THREAD

**Issue by moyger** [la-haute-societe/craft-elasticsearch#1]
Hello, 

This is really a great plugin. It could be super awesome if this can also index Craft Commerce products. Would that be possible?

Thanks, 
Karlo

**Comment by juban** [comment]
Hi @moyger

First of all, thank you for your interest in the plugin and your feedback. It means a lot to us to have those. 

Regarding that feature, sure it will be a great addition to Commerce sites. As we did not use Craft Commerce for production yet, we didn’t focus on that but will put that on the top our backlog. 

Please let us know if you have any specific use case you would like to address. 

Thanks again.

**Comment by juban** [comment]
Hi @moyger,

We just release 1.1.0-beta.1 version with Craft Commerce support.
Could tell us if that works for you and if you have any issues or additional enhancements regarding that feature?

Thanks.

**Comment by moyger** [comment]
Awesome Juban! Will give it a try. I know this is a naive question, I do need to install elastic search in my localhost or I need to have an at least free trial of elastic cloud, right? Just so, to make it work?

**Comment by juban** [comment]
Hi @moyger,

Yes, obviously you will need at least one accessible Elasticsearch instance, either local or remote, to use the plugin.
You can take a look to our quick setup guide to help you with the installation process if needed: [https://github.com/la-haute-societe/craft-elasticsearch/blob/master/elasticsearch-quickstart.md](https://github.com/la-haute-societe/craft-elasticsearch/blob/master/elasticsearch-quickstart.md)

Regarding Craft Commerce support, please let us know if you have any question or issue with it.

Cheers.

**Comment by juban** [comment]
1.1.0 has been released with Craft Commerce support.
