### ISSUE TITLE
Asset Volume Indexing?

### ISSUE THREAD

**Issue by national-mjudge** [la-haute-societe/craft-elasticsearch#10]
Hi there, this is a great plugin to make connecting to Elasticsearch easier, however we are developing a site that will have a lot (over 1000) of PDF files stored in Craft asset volumes, as well as regular page entries. The plugin doesn't appear to enable indexing of asset volumes at present.

Would it be possible to include asset volumes in the indexing data sent to Elasticsearch, either through some code in a module, or by modifying the plugin?

Some of these assets have additional content fields added through Craft, so it would also be great to include those fields in the indexing, as well as the filename and url.

We are presuming that Elasticsearch would be able to read the content of the PDF files, via the Ingest plugin.

**Comment by nstCactus** [comment]
Sorry for the late reply. 

Version 1.4.0 is out and add assets indexing. At the moment its rather basic: it just indexes all assets from all volumes.

To add support for custom fields, follow [these steps](https://github.com/la-haute-societe/craft-elasticsearch/blob/master/README.md#indexing-of-additional-data)
