### ISSUE TITLE
Install issue craft-elasticsearch on craft cms 3.4.5

### ISSUE THREAD

**Issue by pvaessen** [la-haute-societe/craft-elasticsearch#11]
We would like to install the craft-elasticsearch plug-in on craft cms 3.4.5 on a development box but when we do that a lot of packages are downgraded including craft cms (in our case to 3.1.24).
The command used is: composer require la-haute-societe/craft-elasticsearch:1.2.2
When we then try to render the homepage or any other page or try to access the control panel we get this error message:
Invalid Configuration – yii\base\InvalidConfigException
Failed to instantiate component or class "modules\Module".
↵
Caused by: ReflectionException
Class modules\Module does not exist

in /var/www/infor.com/dev/vendor/yiisoft/yii2/di/Container.php at line 431

There is also a warning during the composer require run:
Writing lock file
Generating optimized autoload files

  Seems you have downgraded Yii Framework from version 2.0.32 to 2.0.17.

  Please check the upgrade notes for possible incompatible changes
  and adjust your application code accordingly.

Any ideas how we can get the craft-elasticsearch to work on craft 3.4.5 ?

Thanks,
-Paul-

**Comment by nstCactus** [comment]
Sorry for the late reply. 

Possibly fixed by 87f1beedd30c760fc0c11076307f16bce46135b0.

If you get this issue again, please reopen.
