### ISSUE TITLE
Blacklisted entries types

### ISSUE THREAD

**Issue by juanjosezg** [la-haute-societe/craft-elasticsearch#14]
Is it possible to blacklisted entry types from the config file?

I have a craft commerce instalation and i want to use elastic search only to search products, and no indexing asset, entries or pages, only product pages.

But when i select the entry tipe from de config CP, the website throws me a 504 error, I have more than 160k products.

**Comment by nstCactus** [comment]
Sorry for the late reply. You can disable indexing:
- entries using the [`blacklistedEntryTypes` setting](https://github.com/la-haute-societe/craft-elasticsearch#blacklistedentrytypes)
- assets using the (undocumented) `blacklistedAssetVolumes` setting.

Example:

```php
<?php return [
  'blacklistedEntryTypes' => ['blogEntry', 'contentPage'], // handles of entry types
  'blacklistedAssetVolumes' => ['images', 'documents'], // handles of asset volumes
];
```
