### ISSUE TITLE
Example config.php has wrong structure

### ISSUE THREAD

**Issue by floatingbits** [la-haute-societe/craft-elasticsearch#18]
The example config file has got three keys on the wrong level: 
`             'resultFormatterCallback'  => function (array $formattedResult, $result) {
...
               },
               'elementContentCallback' => function (\craft\base\ElementInterface $element) {
                   return '<span>Some HTML element content to index</span>';
                },
                'extraFields'              => [...]`
                
These keys look like they belong under `elasticsearchComponentConfig`, but they need to be one level higher!

**Comment by nstCactus** [comment]
Thank you for the heads up!
