### ISSUE TITLE
Elasticsearch request failed with code 400: No processor type exists with name [attachment]

### ISSUE THREAD

**Issue by teamteak** [la-haute-societe/craft-elasticsearch#21]
Getting the following 404 error durring Index:

```
Elasticsearch request failed with code 400. Response body: {"error":{"root_cause":[{"type":"parse_exception","reason":"No processor type exists with name [attachment]","processor_type":"attachment"}],"type":"parse_exception","reason":"No processor type exists with name [attachment]","processor_type":"attachment"},"status":400}
```

<img width="1244" alt="Screen Shot 2021-11-23 at 9 58 43 AM" src="https://user-images.githubusercontent.com/46502964/143048161-2a3ba8bc-44bc-4b9b-8e5a-bdcc52234a9e.png">

**Comment by nstCactus** [comment]
Can you give me more details on this issue? Which version of Elasticsearch are you using?

Could you force the recreation of indices and see if it helps? You can do this using the utility at `/admin/utilities/refresh-elasticsearch-index`.
