### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by stephenn-cogapp** [la-haute-societe/craft-elasticsearch#23]
There is currently no support for Craft 4.

I attach a patch that contains the changes required to get to a working search with.

Craft 4.0.2
PHP 8.1
Elasticsearch 7.17

I do not have the capacity to exhaustively test these changes and therefore am submitting the patch for others to build on, rather than creating a Pull Request.

[craft-elasticsearch-craft-4-fix.txt](https://github.com/la-haute-societe/craft-elasticsearch/files/8772475/craft-elasticsearch-craft-4-fix.txt)

**Comment by nstCactus** [comment]
Closed by 9ed7fe9379e3502fc466d58807f732ed87752294
Version 2.0.0 is out with that change.

Thank you for your help!
