### ISSUE TITLE
Indexing for polish content don't work

### ISSUE THREAD

**Issue by sfsmfc** [la-haute-societe/craft-elasticsearch#26]
If we would like to index polish data into elastic, the indexing fails with message, that analyser stempel coun't not be found. 

Fixed in https://github.com/la-haute-societe/craft-elasticsearch/pull/24.

**Comment by nstCactus** [comment]
Closed by 16d3c4e1712fa6db6d0cd2e1f6c1e45253af743c.

Version 2.1.0 is out with that change.

**Comment by nstCactus** [comment]
Version 1.6.0 is out with that change for Craft 3
