### ISSUE TITLE
Could not connect to the Elasticsearch instance at http://tuneyourapp.com:9200. Please check the endpoint URL and authentication settings.

### ISSUE THREAD

**Issue by sunny-vovance** [la-haute-societe/craft-elasticsearch#31]
Hello,

I have done settings as per the doc and it is working fine on curl even if you access http://tuneyourapp.com:9200/ directly in browser it will return jason. But when we are trying to save settings in craft version "3.7.61", it is giving above error "Please check the endpoint URL".

My question is won't it work with http or have to have compulsory access via https?

Can someone please assist on this?

Thanks,
Sunny

**Comment by nstcactus** [comment]
HTTPS isn't mandatory, the plugin works with HTTP as well. 
I cannot assist you on this issue as it looks like a networking issue. Maybe the server hosting your Craft CMS instance has a firewall that blocks outgoing connections.
