### ISSUE TITLE
User plugin with elastic.cloud

### ISSUE THREAD

**Issue by sunny-vovance** [la-haute-societe/craft-elasticsearch#32]
Hello,

How can we use plugin with elastic.cloud instance? Where can we provide ID and API key in plugin? It is asking only for URL and authentication ID/password?

Any help is appreciated.

Thanks,
Sunny

**Comment by nstcactus** [comment]
Hi sorry for the late reply,

Yes, you can use the plugin with Elastic cloud. 

Here's how to collect the credentials:

- log in to Elastic cloud <img width="1320" alt="image" src="https://github.com/la-haute-societe/craft-elasticsearch/assets/353843/1f9de31c-052d-437c-8d5e-5b9403510dd3">
- you should see a list of your services, locate the desired Elasticsearch instance and click *Manage* <img width="972" alt="image" src="https://github.com/la-haute-societe/craft-elasticsearch/assets/353843/8b7c2b8a-e159-4464-941f-6bc2018b4175">
- click *Copy endpoint* (1) to get the **URL**
- click *Security* (2) and then *Reset password* to define a new **password**
- the **username** is `elastic`
