### ISSUE TITLE
Seems to be an issue with elastic 7.3.0

### ISSUE THREAD

**Issue by playengineio** [la-haute-societe/craft-elasticsearch#8]
I got some strange errors from elastic when running 7.3.0. All issues seems fixed in elastic 6.8.2

**Comment by nstCactus** [comment]
Sorry for the late reply, we've been quite busy these past month. 

We haven't had the chance to investigate compatibility with Elasticsearch 7.x but we'll try and look into it in the coming month.

**Comment by nstCactus** [comment]
After further investigation, I have some (bad) news : currently the library ([yii2-elasticsearch](https://github.com/yiisoft/yii2-elasticsearch)) we use to communicate with Elasticsearch [doesn't support Elasticsearch 7](https://github.com/yiisoft/yii2-elasticsearch/issues/225).

Hence the plugin won't support ES7 or greater for the moment.
